baseurl = "https://daniel-j-h.github.io"
languageCode = "en-us"
title = "Daniel J. H."
theme = "herring-cove"

[params]
  Description = "blog blog blog"
  github = "daniel-j-h"
  twitter = "danieljayh"
